### ISSUE TITLE
Erreur dans l'url cours 5 (Echelles et Axes)

### ISSUE THREAD

**Issue by OdinWermeille** [MediaComem/comem-visualdon#2]
L'adresse où mène le lien sur les slides 6 à 12 du cours 5 est https://d3js.org/d3-scale> au lieu de https://d3js.org/d3-scale.

**Comment by romanoe** [comment]
Hello, corrigé dans ce commit https://github.com/MediaComem/comem-visualdon/commit/becec17914ae8381db3af49c27b55b5c6a916939
